### ISSUE TITLE
Howto load Boot and App ?

### ISSUE THREAD

**Issue by r4d10n** [koao/STM32F7508-DK-to-boot-from-qspi#1]
Hello..

I have been trying to get LCD working on STM32F7508-DK without TouchGFX... I guess I have to load from QSPI...

Could you describe in the README, on how to load these two codes onto the mcu ?

Cheers

**Comment by koao** [comment]
Hello

You can load these two codes into your MCU by opening and running them in the STM32CubeIDE.

Need an explanation of how to operate it?
